matrix:
  include:
    - language: objective-c
      podfile: ios/Podfile
      osx_image: xcode13.1
      os: osx
      sudo: true
      cache:
        - yarn
        - cocoapods
      
      before_install:
        - gem install cocoapods
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 14.17.0
        - brew install yarn
        - cd ios && gem install bundler && cd ..
        - cd ios && pod repo update && cd ..
        - ./Tools/updateVersion.sh
      
      install:
        - yarn install
        - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
        # https://stackoverflow.com/questions/69427082/problem-with-cocoapods-showing-error-couldnt-determine-repo-type-for-url-whe
        - chmod 0600 ~/.netrc
        - cd ios && bundle install && bundle update fastlane && pod install && cd ..
        - cd ios && bundle exec fastlane install_certificates && bundle exec fastlane match appstore && cd ..

      script:
        - cd ios && bundle exec fastlane release && cd ..

      deploy:
        skip_cleanup: true
        provider: script
        script: cd ios && bundle exec fastlane distribute_to_testflight && cd ..
        on:
          branch: master
          condition: '-n "$LEANPLUM_SDK_VERSION"'
      # deploy:
      #   skip_cleanup: true
      #   provider: releases
      #   api_key:
      #     secure: MWlFQyijuDqSehsQCHuLM3TbW4S587HlCvgKLu4yFGtHbYhC5sXwQDZCSss/7NQseWNa8pQz/NxMN4AtxEvZQIvi/yQ6R3DdyfpY3nmpJCgpLz4lIAGnkirugpVczvf9myS9oBNreIM2X9tjqqrwtFUnxetBepdoE/gKkH1ek6hZac6IyQyPu6ObFFrxVBzE6+L1KVCZY75Q1RFbgSPgj5ZquGX9l792AYEPD6rb5QY0U0yD5qTHqIZJquy0XlO7xukZCsYIRsCq0VStlqC+2udm+0sjcmjqWunQDPHylBQySnTk7CRAqziUnSfbmugvgnwW2evMAr+aFioBDAKBL00WCZ+nppO1dI1a05iESjvMfld5+wk6xBDjtk1A3CT+2+0YRtdrFU6KkdK/kNtbQNpsv0TFC58ILnY8cZLPurzr4khwIbSTKjygm5Xdbi1ZddxfxjsGPycRVq+/kkhaeGbHwhAVickA8e9uCV8gA4rR4OsKvoovp5AoAGhrYdBaKFybkf+4IPkOPq8kSVPixLJPlYtgvLHI6J8Nub+Ln+74aQouOE++hm3oWFvNrLqcvGHFZ8URky/N9C3OFmv43qcj6upiJzFTB2T4v0Lj5u0HxeRzn71rOZq/WIu6A8/OI0Lto7gPl7PnPtTTW6s+wMa/la+g0/6RCpFKP9CcsCI=
      #   file: '$TRAVIS_BUILD_DIR/ios/build/RondoApp.ipa'
      #   name: 'React Native SDK $LEANPLUM_SDK_VERSION'
      #   tag: '$LEANPLUM_SDK_VERSION'
      #   on:
      #     branch: develop
      #     condition: '-n "$LEANPLUM_SDK_VERSION"'
    
    - language: android
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - tools
          - extra-google-google_play_services
          - extra-google-m2repository
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - touch $HOME/.android/repositories.cfg
        - yes | sdkmanager "platforms;android-31"
        - yes | sdkmanager "build-tools;31.0.0"
        - nvm install 14.17.0
        - node --version
        - ./Tools/updateVersion.sh

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.android/build-cache

      jdk:
        - oraclejdk11

      install:
        - npm install
        - npm run ci
      

      script:
        - sdkmanager --list
        - mkdir -p android/app/src/main/assets
        - npx react-native bundle --platform android --dev false --entry-file index.js
          --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest
          android/app/src/main/res/
        - cd android && ./gradlew assembleDebug && cd ..

      deploy:
        skip_cleanup: true
        edge: true
        provider: releases
        api_key: $GITHUB_TOKEN
        file: '$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/debug/app-debug.apk'
        name: 'React Native SDK $LEANPLUM_SDK_VERSION'
        tag: '$LEANPLUM_SDK_VERSION'
        on:
          branch: master
          condition: '-n "$LEANPLUM_SDK_VERSION"'
        
