matrix:
  include:
    - language: objective-c
      podfile: ios/Podfile
      osx_image: xcode10.1
      os: osx
      sudo: true
      cache:
        - yarn
        - cocoapods
      before_install:
        - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8.12.0
        - brew install yarn
      install:
        - yarn install
        - cd ios && pod install && cd ..
      script:
        - sh ios/ios.sh
    - language: android
      before_install:
        - nvm install 8
        - node --version
      install:
        - npm install
        - npm run ci
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - npx react-native bundle --platform android --dev false --entry-file index.js
          --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest
          android/app/src/main/res/
        - cd android && ./gradlew assembleDebug
      deploy:
        skip_cleanup: true
        provider: releases
        api_key:
          secure: MWlFQyijuDqSehsQCHuLM3TbW4S587HlCvgKLu4yFGtHbYhC5sXwQDZCSss/7NQseWNa8pQz/NxMN4AtxEvZQIvi/yQ6R3DdyfpY3nmpJCgpLz4lIAGnkirugpVczvf9myS9oBNreIM2X9tjqqrwtFUnxetBepdoE/gKkH1ek6hZac6IyQyPu6ObFFrxVBzE6+L1KVCZY75Q1RFbgSPgj5ZquGX9l792AYEPD6rb5QY0U0yD5qTHqIZJquy0XlO7xukZCsYIRsCq0VStlqC+2udm+0sjcmjqWunQDPHylBQySnTk7CRAqziUnSfbmugvgnwW2evMAr+aFioBDAKBL00WCZ+nppO1dI1a05iESjvMfld5+wk6xBDjtk1A3CT+2+0YRtdrFU6KkdK/kNtbQNpsv0TFC58ILnY8cZLPurzr4khwIbSTKjygm5Xdbi1ZddxfxjsGPycRVq+/kkhaeGbHwhAVickA8e9uCV8gA4rR4OsKvoovp5AoAGhrYdBaKFybkf+4IPkOPq8kSVPixLJPlYtgvLHI6J8Nub+Ln+74aQouOE++hm3oWFvNrLqcvGHFZ8URky/N9C3OFmv43qcj6upiJzFTB2T4v0Lj5u0HxeRzn71rOZq/WIu6A8/OI0Lto7gPl7PnPtTTW6s+wMa/la+g0/6RCpFKP9CcsCI=
        file: '$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/debug/app-debug.apk'
        on:
          tags: true
          repo: Leanplum/Rondo-ReactNative
          branch: travis-build
