matrix:
  include:
    - language: objective-c
      podfile: ios/Podfile
      osx_image: xcode13.1
      os: osx
      sudo: true
      cache:
        - yarn
        - cocoapods
      
      before_install:
        - gem install cocoapods
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 14.17.0
        - brew install yarn
        - cd ios && gem install bundler && cd ..
        - cd ios && pod repo update && cd ..
        - ./Tools/updateVersion.sh
      
      install:
        - yarn install
        - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
        # https://stackoverflow.com/questions/69427082/problem-with-cocoapods-showing-error-couldnt-determine-repo-type-for-url-whe
        - chmod 0600 ~/.netrc
        - cd ios && bundle install && bundle update fastlane && pod install && cd ..
        - cd ios && bundle exec fastlane install_certificates && bundle exec fastlane match appstore && cd ..

      script:
        - cd ios && bundle exec fastlane release && cd ..

      deploy:
        skip_cleanup: true
        provider: script
        script: cd ios && bundle exec fastlane distribute_to_testflight && cd ..
        on:
          branch: master
          condition: '-n "$LEANPLUM_SDK_VERSION"'
      # deploy:
      #   skip_cleanup: true
      #   provider: releases
      #   api_key:
      #     secure: MWlFQyijuDqSehsQCHuLM3TbW4S587HlCvgKLu4yFGtHbYhC5sXwQDZCSss/7NQseWNa8pQz/NxMN4AtxEvZQIvi/yQ6R3DdyfpY3nmpJCgpLz4lIAGnkirugpVczvf9myS9oBNreIM2X9tjqqrwtFUnxetBepdoE/gKkH1ek6hZac6IyQyPu6ObFFrxVBzE6+L1KVCZY75Q1RFbgSPgj5ZquGX9l792AYEPD6rb5QY0U0yD5qTHqIZJquy0XlO7xukZCsYIRsCq0VStlqC+2udm+0sjcmjqWunQDPHylBQySnTk7CRAqziUnSfbmugvgnwW2evMAr+aFioBDAKBL00WCZ+nppO1dI1a05iESjvMfld5+wk6xBDjtk1A3CT+2+0YRtdrFU6KkdK/kNtbQNpsv0TFC58ILnY8cZLPurzr4khwIbSTKjygm5Xdbi1ZddxfxjsGPycRVq+/kkhaeGbHwhAVickA8e9uCV8gA4rR4OsKvoovp5AoAGhrYdBaKFybkf+4IPkOPq8kSVPixLJPlYtgvLHI6J8Nub+Ln+74aQouOE++hm3oWFvNrLqcvGHFZ8URky/N9C3OFmv43qcj6upiJzFTB2T4v0Lj5u0HxeRzn71rOZq/WIu6A8/OI0Lto7gPl7PnPtTTW6s+wMa/la+g0/6RCpFKP9CcsCI=
      #   file: '$TRAVIS_BUILD_DIR/ios/build/RondoApp.ipa'
      #   name: 'React Native SDK $LEANPLUM_SDK_VERSION'
      #   tag: '$LEANPLUM_SDK_VERSION'
      #   on:
      #     branch: develop
      #     condition: '-n "$LEANPLUM_SDK_VERSION"'
    
    - language: android
      env:
        global:
          - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
          - BUILD_API=31
          - BUILD_TOOLS=31.0.0
          - ANDROID_HOME=/usr/local/android-sdk
          - TOOLS=${ANDROID_HOME}/cmdline-tools/latest
          # PATH order is important, the 'emulator' script exists in more than one place
          - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
      
      jdk:
        - oraclejdk11
      
      android:
        components:
          - tools
      
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      
      before_install:
        # Install cmdline-tools (older tools doesn't support Java 11)
        - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-commandline-tools-linux.zip
        - mkdir -p ${ANDROID_HOME}/cmdline-tools
        - unzip -q android-commandline-tools-linux.zip -d ${ANDROID_HOME}/cmdline-tools
        - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
        - nvm install 14.17.0
        - node --version
        - ./Tools/updateVersion.sh
      
      before_script:
        # Install Android SDK
        - echo 'count=0' > /home/travis/.android/repositories.cfg # avoid harmless sdkmanager warning
        - echo y | ${TOOLS}/bin/sdkmanager "platform-tools" >/dev/null
        - echo y | ${TOOLS}/bin/sdkmanager "tools" >/dev/null
        - echo y | ${TOOLS}/bin/sdkmanager "build-tools;$BUILD_TOOLS" >/dev/null
        - echo y | ${TOOLS}/bin/sdkmanager "platforms;android-$BUILD_API" >/dev/null
        - echo y | ${TOOLS}/bin/sdkmanager "extras;android;m2repository" >/dev/null

      install:
        - npm install
        - npm run ci

      script:
        - sdkmanager --list
        - mkdir -p android/app/src/main/assets
        - npx react-native bundle --platform android --dev false --entry-file index.js
          --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest
          android/app/src/main/res/
        - cd android && ./gradlew assembleDebug && cd ..

      deploy:
        skip_cleanup: true
        edge: true
        provider: releases
        api_key: $GITHUB_TOKEN
        file: '$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/debug/app-debug.apk'
        name: 'React Native SDK $LEANPLUM_SDK_VERSION'
        tag: '$LEANPLUM_SDK_VERSION'
        on:
          branch: master
          condition: '-n "$LEANPLUM_SDK_VERSION"'
        
