require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

inhibit_all_warnings!

target 'RondoApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # pod 'Leanplum-iOS-Location', '3.1.2'
  # pod 'Leanplum-iOS-LocationAndBeacons', '3.1.2'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()
  use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })

  dynamic_frameworks = ['Leanplum-iOS-SDK']
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if dynamic_frameworks.include?(pod.name)
          puts "Setting dynamic linking for #{pod.name}"
          def pod.build_type;
            Pod::BuildType.dynamic_framework
          end
        end
      end
  end
  
  post_install do |installer|
    react_native_post_install(installer)
  end
end
